### ISSUE TITLE
improve the error messages when incorrectly specifying pkgr.yml path

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/pkgr#126]
```
pkgr plan --library=/data/johnsmith/lib --config=/data/johnsmith
INFO[0000] Installation would launch 7 workers
INFO[0000] R Version 3.5.1
INFO[0000] OS Platform x86_64-pc-linux-gnu
INFO[0000] found installed packages                      count=99
PANI[0000] error getting pkgdb  Package database must contain at least one RepoUrl
panic: (*logrus.Entry) (0x9da7e0,0xc0004b38f0)
goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc0000ba1e0, 0xc00052c390, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/devinpastoor/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:239 +0x2ce
github.com/sirupsen/logrus.(*Entry).Log(0xc0004b2000, 0x0, 0xc00013ac48, 0x1, 0x1)
        /Users/devinpastoor/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:268 +0xed
github.com/sirupsen/logrus.(*Entry).Logln(0xc0004b2000, 0xc000000000, 0xc00013afb0, 0x2, 0x2)
        /Users/devinpastoor/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:359 +0xd3
github.com/sirupsen/logrus.(*Logger).Logln(0xc0000ba1e0, 0x0, 0xc00013afb0, 0x2, 0x2)
        /Users/devinpastoor/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:239 +0x7f
github.com/sirupsen/logrus.(*Logger).Panicln(...)
        /Users/devinpastoor/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:280
github.com/sirupsen/logrus.Panicln(...)
        /Users/devinpastoor/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/exported.go:219
github.com/metrumresearchgroup/pkgr/cmd.planInstall(0x3, 0x5, 0x1, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/devinpastoor/go/src/github.com/metrumresearchgroup/pkgr/cmd/plan.go:95 +0x6ab
github.com/metrumresearchgroup/pkgr/cmd.plan(0xe65700, 0xc0000c4fe0, 0x0, 0x2, 0x0, 0x0)
        /Users/devinpastoor/go/src/github.com/metrumresearchgroup/pkgr/cmd/plan.go:61 +0x443
github.com/spf13/cobra.(*Command).execute(0xe65700, 0xc0000c4f60, 0x2, 0x2, 0xe65700, 0xc0000c4f60)
        /Users/devinpastoor/go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:762 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0xe65bc0, 0x13, 0xc00013bf38, 0x1)
        /Users/devinpastoor/go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:850 +0x2bb
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/devinpastoor/go/pkg/mod/github.com/spf13/cobra@v0.0.4/command.go:800
github.com/metrumresearchgroup/pkgr/cmd.Execute(0x0, 0x0)
        /Users/devinpastoor/go/src/github.com/metrumresearchgroup/pkgr/cmd/root.go:49 +0xe6
main.main()
        /Users/devinpastoor/go/src/github.com/metrumresearchgroup/pkgr/cmd/pkgr/pkgr.go:17 +0x39
```

where config should actually be `/data/johnsmith/pkgr.yml`

Error should be like "no pkgr.yml file detected at path.... please...."

**Comment by Dreznel** [comment]
Acceptance Criteria:
- When pkgr.yml path is incorrectly specified, the program stops and a clear error message describing the problem (invalid path given) is displayed.

**Comment by Dreznel** [comment]
Would it be possible to provide more detail on the issue as it exists now? Did e5cf0c3 address the AC?
