### ISSUE TITLE
pkgr throws error for 2020-09-20 snapshot

### ISSUE THREAD

**Issue by copernican** [metrumresearchgroup/pkgr#306]
`pkgr plan` throws an error with a minimal `pkgr.yml`. It may be particular to the (previously working) 2020-09-20 snapshot.

```sh
➜  /tmp cat pkgr.yml
Version: 1

Packages:
  - dplyr

Repos:
  - MPN: https://mpn.metworx.com/snapshots/stable/2020-09-20

Lockfile:
    Type: renv

➜  /tmp pkgr plan
INFO[0000] Installation would launch 8 workers
INFO[0000] R Version 3.6.2
INFO[0000] Package Library will be created               path=renv/library/R-3.6/x86_64-pc-linux-gnu
ERRO[0000] error downloading repo information            error="<nil>" repo=MPN url="https://mpn.metworx.com/snapshots/stable/2020-09-20"
PANI[0000] error getting pkgdb  EOF
panic: (*logrus.Entry) (0xb77660,0xc000129650)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc0000b15e0, 0xc0001507e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/devinp/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:239 +0x2db
github.com/sirupsen/logrus.(*Entry).Log(0xc000128620, 0x0, 0xc000105c00, 0x1, 0x1)
	/Users/devinp/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:268 +0xeb
github.com/sirupsen/logrus.(*Entry).Logln(0xc000128620, 0xc000000000, 0xc0001060f8, 0x2, 0x2)
	/Users/devinp/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:359 +0xd1
github.com/sirupsen/logrus.(*Logger).Logln(0xc0000b15e0, 0x0, 0xc0001060f8, 0x2, 0x2)
	/Users/devinp/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:239 +0x7d
github.com/sirupsen/logrus.(*Logger).Panicln(...)
	/Users/devinp/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:280
github.com/sirupsen/logrus.Panicln(...)
	/Users/devinp/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/exported.go:219
github.com/metrumresearchgroup/pkgr/cmd.planInstall(0x3, 0x6, 0x2, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/devinp/go/src/github.com/metrumresearchgroup/pkgr/cmd/plan.go:137 +0x888
github.com/metrumresearchgroup/pkgr/cmd.plan(0x115f060, 0x11879f0, 0x0, 0x0, 0x0, 0x0)
	/Users/devinp/go/src/github.com/metrumresearchgroup/pkgr/cmd/plan.go:66 +0x440
github.com/spf13/cobra.(*Command).execute(0x115f060, 0x11879f0, 0x0, 0x0, 0x115f060, 0x11879f0)
	/Users/devinp/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0x115fa60, 0x13, 0xc000107f00, 0x1)
	/Users/devinp/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/devinp/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/metrumresearchgroup/pkgr/cmd.Execute(0x0, 0x0)
	/Users/devinp/go/src/github.com/metrumresearchgroup/pkgr/cmd/root.go:50 +0xe5
main.main()
	/Users/devinp/go/src/github.com/metrumresearchgroup/pkgr/cmd/pkgr/pkgr.go:17 +0x39
```

But the behavior is as expected with the previous snapshot (2020-08-15).

```sh
➜  /tmp cat pkgr.yml
Version: 1

Packages:
  - dplyr

Repos:
  - MPN: https://mpn.metworx.com/snapshots/stable/2020-08-15

Lockfile:
    Type: renv
```

Guessing this is a snapshot issue rather than a pkgr issue, but it would be nice if pkgr threw a more informative error. Note that this is pkgr 1.0.2.

```sh
➜  /tmp pkgr |grep version
pkgr cli version 1.0.2
```

**Comment by copernican** [comment]
This may actually be a pkgr issue, because this works as expected:

```r
install.packages("broom", repos = "https://mpn.metworx.com/snapshots/stable/2020-09-20")
```

**Comment by copernican** [comment]
The same issue appears to also affect the latest release.

```sh
➜  /tmp ~/pkgr | grep version
pkgr cli version v1.2.1
➜  /tmp ~/pkgr plan
INFO[0000] Installation would launch 8 workers
INFO[0000] R Version 3.6.2
INFO[0000] Package Library will be created               path=renv/library/R-3.6/x86_64-pc-linux-gnu
ERRO[0000] error downloading repo information            error="<nil>" repo=MPN url="https://mpn.metworx.com/snapshots/stable/2020-09-20"
PANI[0000] error getting pkgdb  EOF
panic: (*logrus.Entry) (0xb72660,0xc0001da690)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc0001155e0, 0xc0001b6db0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/devinp/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:259 +0x335
github.com/sirupsen/logrus.(*Entry).Log(0xc000178c40, 0x0, 0xc0001678b8, 0x1, 0x1)
	/Users/devinp/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:287 +0xeb
github.com/sirupsen/logrus.(*Entry).Logln(0xc000178c40, 0xc000000000, 0xc000167de0, 0x2, 0x2)
	/Users/devinp/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:378 +0xd1
github.com/sirupsen/logrus.(*Logger).Logln(0xc0001155e0, 0x0, 0xc000167de0, 0x2, 0x2)
	/Users/devinp/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/logger.go:240 +0x7d
github.com/sirupsen/logrus.(*Logger).Panicln(...)
	/Users/devinp/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/logger.go:281
github.com/sirupsen/logrus.Panicln(...)
	/Users/devinp/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/exported.go:219
github.com/metrumresearchgroup/pkgr/cmd.planInstall(0x3, 0x6, 0x2, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/devinp/go/src/github.com/metrumresearchgroup/pkgr/cmd/plan.go:155 +0xb60
github.com/metrumresearchgroup/pkgr/cmd.plan(0x1183c00, 0x11ba888, 0x0, 0x0, 0x0, 0x0)
	/Users/devinp/go/src/github.com/metrumresearchgroup/pkgr/cmd/plan.go:66 +0x440
github.com/spf13/cobra.(*Command).execute(0x1183c00, 0x11ba888, 0x0, 0x0, 0x1183c00, 0x11ba888)
	/Users/devinp/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0x1184680, 0x13, 0xc000169f28, 0x1)
	/Users/devinp/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/devinp/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
github.com/metrumresearchgroup/pkgr/cmd.Execute(0x0, 0x0)
	/Users/devinp/go/src/github.com/metrumresearchgroup/pkgr/cmd/root.go:49 +0xe5
main.main()
	/Users/devinp/go/src/github.com/metrumresearchgroup/pkgr/cmd/pkgr/pkgr.go:17 +0x39
```

**Comment by dpastoor** [comment]
From the error it's saying it had a problem with the package database this likely means something went sideways during the initial query and now you have a corrupted DB in your cache. The solve is to clear your cache and should be back in business. The error itself gets masked by the subsequent panicking.

This is definitely a rough edge case around the resiliency of the cache especially because of a number of places we just warn interactively but then plow forward

**Comment by copernican** [comment]
That appears to work for the minimal example above, but when I try it on my actual project, `pkgr clean` throws an error.

```sh
➜  proj_dir ~/pkgr | grep version
pkgr cli version v1.2.1
➜  proj_dir ~/pkgr clean pkgdbs
INFO[0000] found installed packages                      count=157
WARN[0000] Packages not installed by pkgr                packages="[TMB cubelyr renv broom.mixed broom]"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x88e129]

goroutine 49 [running]:
github.com/metrumresearchgroup/pkgr/cran.(*RepoDb).FetchPackages.func1(0xc00058e000, 0x3, 0x6, 0x2, 0xc00059a1e0, 0xc0005a0d40, 0x1)
	/Users/devinp/go/src/github.com/metrumresearchgroup/pkgr/cran/repodb.go:154 +0x1d9
created by github.com/metrumresearchgroup/pkgr/cran.(*RepoDb).FetchPackages
	/Users/devinp/go/src/github.com/metrumresearchgroup/pkgr/cran/repodb.go:146 +0x306
```

If I manually remove `~/.cache/pkgr`, I get a different error from `pkgr plan`.

```sh
➜  ~ rm -rf .cache/pkgr
➜  proj_dir ~/pkgr clean pkgdbs
INFO[0000] found installed packages                      count=157
WARN[0000] Packages not installed by pkgr                packages="[cubelyr broom.mixed TMB broom renv]"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x88e129]

goroutine 10 [running]:
github.com/metrumresearchgroup/pkgr/cran.(*RepoDb).FetchPackages.func1(0xc000223490, 0x3, 0x6, 0x2, 0xc000217320, 0xc000235b00, 0x1)
	/Users/devinp/go/src/github.com/metrumresearchgroup/pkgr/cran/repodb.go:154 +0x1d9
created by github.com/metrumresearchgroup/pkgr/cran.(*RepoDb).FetchPackages
	/Users/devinp/go/src/github.com/metrumresearchgroup/pkgr/cran/repodb.go:146 +0x306
➜  proj_dir ~/pkgr plan
INFO[0000] Installation would launch 8 workers
INFO[0000] R Version 3.6.2
INFO[0000] found installed packages                      count=157
WARN[0000] Packages not installed by pkgr                packages="[cubelyr TMB renv broom.mixed broom]"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x88e129]

goroutine 14 [running]:
github.com/metrumresearchgroup/pkgr/cran.(*RepoDb).FetchPackages.func1(0xc0001792d0, 0x3, 0x6, 0x2, 0xc0001ed080, 0xc000291520, 0x1)
	/Users/devinp/go/src/github.com/metrumresearchgroup/pkgr/cran/repodb.go:154 +0x1d9
created by github.com/metrumresearchgroup/pkgr/cran.(*RepoDb).FetchPackages
	/Users/devinp/go/src/github.com/metrumresearchgroup/pkgr/cran/repodb.go:146 +0x306
```

**Comment by dpastoor** [comment]
I am unable to reproduce this on both linux and mac

![image](https://user-images.githubusercontent.com/3196313/97164260-3f360d80-1758-11eb-912b-bff7f60a53ca.png)

Lets start on the workarounds:

First one is here: https://github.com/metrumresearchgroup/pkgr/blob/c3d9a7d70b02a4ee59c82ecf10def7f162f9a5f4/cran/repodb.go#L110

I would be curious to see if you definitely forced a cache invalidation if it works:

```
R_AVAILABLE_PACKAGES_CACHE_CONTROL_MAX_AGE=0 pkgr plan
```

If that doesn't work, for the project esp I would want to hop on a diagnostic screen share to poke at the system a little bit (eg the cache directory, the library folder, permissions) to see if we could mirror those and get a reproducible error.


If you still do have the error the other thing I'd want to do is give you a patched version to see what the actual error is - the specific problem is pretty clear actually:

https://github.com/metrumresearchgroup/pkgr/blob/master/cran/repodb.go#L153


```
				res, err := http.Get(pkgURL)
				if res.StatusCode != 200 {
					downloadChannel <- downloadDatabase{
						St:                    st,
						AvailableDescriptions: descriptionMap,
						Err:                   fmt.Errorf("failed fetching PACKAGES file from %s, with status %s", pkgURL, res.Status)}
					return
				}
				if err != nil {
					err = fmt.Errorf("problem getting packages from url %s: %s", pkgURL, err)
					downloadChannel <- downloadDatabase{St: st, AvailableDescriptions: descriptionMap, Err: err}
					return
				}

				defer res.Body.Close()
```

2 year ago me was pretty dumb and went to check the statusCode of the result before checking that the err was nil (which I do below). That panic is referencing elements on an object that don't exist - aka very clearly that http.Get is returning an error and a bad response, potentially nil.

I can give you a patched version that properly handles that error and see what exactly you saw.
